# CMake generated Testfile for 
# Source directory: /mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD
# Build directory: /mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_adaptive_level "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_adaptive_level")
set_tests_properties(test_adaptive_level PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_alternative_allocation_strategies "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_alternative_allocation_strategies")
set_tests_properties(test_alternative_allocation_strategies PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_basic_profile "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_basic_profile")
set_tests_properties(test_basic_profile PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_checksum_validation "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_checksum_validation")
set_tests_properties(test_checksum_validation PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_comprehensive_fallback "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_comprehensive_fallback")
set_tests_properties(test_comprehensive_fallback PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_compressible_data "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_compressible_data")
set_tests_properties(test_compressible_data PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_correctness "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_correctness")
set_tests_properties(test_correctness PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_coverage_gaps "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_coverage_gaps")
set_tests_properties(test_coverage_gaps PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_debug_infrastructure "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_debug_infrastructure")
set_tests_properties(test_debug_infrastructure PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_dictionary "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_dictionary")
set_tests_properties(test_dictionary PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_dictionary_compression "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_dictionary_compression")
set_tests_properties(test_dictionary_compression PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_error_handling "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_error_handling")
set_tests_properties(test_error_handling PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_extended_validation "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_extended_validation")
set_tests_properties(test_extended_validation PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_fallback_strategies "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_fallback_strategies")
set_tests_properties(test_fallback_strategies PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_find_matches_small "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_find_matches_small")
set_tests_properties(test_find_matches_small PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_fse_advanced "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_fse_advanced")
set_tests_properties(test_fse_advanced PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_fse_advanced_function "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_fse_advanced_function")
set_tests_properties(test_fse_advanced_function PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_fse_reference_comparison "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_fse_reference_comparison")
set_tests_properties(test_fse_reference_comparison PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_hash_chain_only "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_hash_chain_only")
set_tests_properties(test_hash_chain_only PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_huffman "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_huffman")
set_tests_properties(test_huffman PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_integration "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_integration")
set_tests_properties(test_integration PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_lz77_comprehensive "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_lz77_comprehensive")
set_tests_properties(test_lz77_comprehensive PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_manager_only "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_manager_only")
set_tests_properties(test_manager_only PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool")
set_tests_properties(test_memory_pool PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_deallocate_timeout "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_deallocate_timeout")
set_tests_properties(test_memory_pool_deallocate_timeout PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_double_free "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_double_free")
set_tests_properties(test_memory_pool_double_free PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_double_free_fixed "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_double_free_fixed")
set_tests_properties(test_memory_pool_double_free_fixed PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_double_free_race "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_double_free_race")
set_tests_properties(test_memory_pool_double_free_race PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_double_free_race_fixed "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_double_free_race_fixed")
set_tests_properties(test_memory_pool_double_free_race_fixed PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_lock_ordering "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_lock_ordering")
set_tests_properties(test_memory_pool_lock_ordering PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_memory_pool_lock_timeout "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_memory_pool_lock_timeout")
set_tests_properties(test_memory_pool_lock_timeout PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_metadata_roundtrip "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_metadata_roundtrip")
set_tests_properties(test_metadata_roundtrip PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_minimal_compress "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_minimal_compress")
set_tests_properties(test_minimal_compress PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_minimal_create "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_minimal_create")
set_tests_properties(test_minimal_create PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_minimal_manager "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_minimal_manager")
set_tests_properties(test_minimal_manager PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_multi_iteration "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_multi_iteration")
set_tests_properties(test_multi_iteration PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_multitable_fse "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_multitable_fse")
set_tests_properties(test_multitable_fse PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_nvcomp_batch "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_nvcomp_batch")
set_tests_properties(test_nvcomp_batch PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_nvcomp_interface "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_nvcomp_interface")
set_tests_properties(test_nvcomp_interface PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_parallel_backtracking "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_parallel_backtracking")
set_tests_properties(test_parallel_backtracking PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_parallel_compression "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_parallel_compression")
set_tests_properties(test_parallel_compression PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_perf_simple "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_perf_simple")
set_tests_properties(test_perf_simple PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_performance "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_performance")
set_tests_properties(test_performance PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_roundtrip "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_roundtrip")
set_tests_properties(test_roundtrip PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_simple_fse_reference "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_simple_fse_reference")
set_tests_properties(test_simple_fse_reference PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_stream_pool "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_stream_pool")
set_tests_properties(test_stream_pool PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_stream_pool_timeout "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_stream_pool_timeout")
set_tests_properties(test_stream_pool_timeout PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_streaming "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_streaming")
set_tests_properties(test_streaming PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_timing "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_timing")
set_tests_properties(test_timing PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_twice "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_twice")
set_tests_properties(test_twice PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_ultra_minimal "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_ultra_minimal")
set_tests_properties(test_ultra_minimal PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_workspace_patterns "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_workspace_patterns")
set_tests_properties(test_workspace_patterns PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;153;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(test_c_api "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/test_c_api")
set_tests_properties(test_c_api PROPERTIES  TIMEOUT "100" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;163;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
add_test(level_nvcomp_demo "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/build_v32/level_nvcomp_demo")
set_tests_properties(level_nvcomp_demo PROPERTIES  TIMEOUT "100" _BACKTRACE_TRIPLES "/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;173;add_test;/mnt/d/Research Experiments/TDPE_and_GPU_loading/NVComp with ZSTD/CMakeLists.txt;0;")
subdirs("_deps/zstd-build")
